//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Escc.FormControls.WebForms.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class EsccWebTeam_FormControls {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EsccWebTeam_FormControls() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Escc.FormControls.WebForms.Properties.EsccWebTeam_FormControls", typeof(EsccWebTeam_FormControls).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to County.
        /// </summary>
        internal static string AdministrativeAreaLabel {
            get {
                return ResourceManager.GetString("AdministrativeAreaLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to button buttonBig.
        /// </summary>
        internal static string ButtonConfirmAddressClass {
            get {
                return ResourceManager.GetString("ButtonConfirmAddressClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find address.
        /// </summary>
        internal static string ButtonFindAddress {
            get {
                return ResourceManager.GetString("ButtonFindAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to button.
        /// </summary>
        internal static string ButtonFindAddressClass {
            get {
                return ResourceManager.GetString("ButtonFindAddressClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to button buttonBigger.
        /// </summary>
        internal static string ButtonManualAddressClass {
            get {
                return ResourceManager.GetString("ButtonManualAddressClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm address.
        /// </summary>
        internal static string ConfirmAddress {
            get {
                return ResourceManager.GetString("ConfirmAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your personal details are protected when using our online forms. Read our &lt;a href=&quot;/about/privacypolicy/&quot;&gt;privacy statement&lt;/a&gt;..
        /// </summary>
        internal static string DataProtectionText {
            get {
                return ResourceManager.GetString("DataProtectionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of birth.
        /// </summary>
        internal static string DateofBirthEntryPrompt {
            get {
                return ResourceManager.GetString("DateofBirthEntryPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AM or PM.
        /// </summary>
        internal static string DatePartAMPMEntryPrompt {
            get {
                return ResourceManager.GetString("DatePartAMPMEntryPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day .
        /// </summary>
        internal static string DatePartDayEntryPrompt {
            get {
                return ResourceManager.GetString("DatePartDayEntryPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hour.
        /// </summary>
        internal static string DatePartHourEntryPrompt {
            get {
                return ResourceManager.GetString("DatePartHourEntryPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minutes.
        /// </summary>
        internal static string DatePartMinuteEntryPrompt {
            get {
                return ResourceManager.GetString("DatePartMinuteEntryPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month .
        /// </summary>
        internal static string DatePartMonthEntryPrompt {
            get {
                return ResourceManager.GetString("DatePartMonthEntryPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year .
        /// </summary>
        internal static string DatePartYearEntryPrompt {
            get {
                return ResourceManager.GetString("DatePartYearEntryPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a month and year as well as a day.
        /// </summary>
        internal static string DateRequiresMoreThanDayError {
            get {
                return ResourceManager.GetString("DateRequiresMoreThanDayError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a day and year as well as a month.
        /// </summary>
        internal static string DateRequiresMoreThanMonthError {
            get {
                return ResourceManager.GetString("DateRequiresMoreThanMonthError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a day and month as well as a year.
        /// </summary>
        internal static string DateRequiresMoreThanYearError {
            get {
                return ResourceManager.GetString("DateRequiresMoreThanYearError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the day of the month.
        /// </summary>
        internal static string DaySelectPopupText {
            get {
                return ResourceManager.GetString("DaySelectPopupText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter an address.
        /// </summary>
        internal static string ErrorAddressBlank {
            get {
                return ResourceManager.GetString("ErrorAddressBlank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please click &apos;Find address&apos; to complete your address.
        /// </summary>
        internal static string ErrorAddressPostcodeOnly {
            get {
                return ResourceManager.GetString("ErrorAddressPostcodeOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some of the characters in the county name are not allowed.
        /// </summary>
        internal static string ErrorAdministrativeAreaFormat {
            get {
                return ResourceManager.GetString("ErrorAdministrativeAreaFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please use 30 characters or fewer in the county name.
        /// </summary>
        internal static string ErrorAdministrativeAreaLength {
            get {
                return ResourceManager.GetString("ErrorAdministrativeAreaLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select the hour and minute of the time.
        /// </summary>
        internal static string ErrorHourMinuteRequireEachOther {
            get {
                return ResourceManager.GetString("ErrorHourMinuteRequireEachOther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some of the characters in the fourth line of your address are not allowed.
        /// </summary>
        internal static string ErrorLocalityFormat {
            get {
                return ResourceManager.GetString("ErrorLocalityFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please use 35 characters or fewer in the fourth line of your address.
        /// </summary>
        internal static string ErrorLocalityLength {
            get {
                return ResourceManager.GetString("ErrorLocalityLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interval between minutes to list must be at least 1.
        /// </summary>
        internal static string ErrorMinuteInterval {
            get {
                return ResourceManager.GetString("ErrorMinuteInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some of the characters in the second line of your address are not allowed.
        /// </summary>
        internal static string ErrorPaonFormat {
            get {
                return ResourceManager.GetString("ErrorPaonFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please use 100 characters or fewer in the second line of your address.
        /// </summary>
        internal static string ErrorPaonLength {
            get {
                return ResourceManager.GetString("ErrorPaonLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No addresses were found for the postcode supplied.
        /// </summary>
        internal static string ErrorPostcodeNotFound {
            get {
                return ResourceManager.GetString("ErrorPostcodeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a postcode.
        /// </summary>
        internal static string ErrorPostcodeRequired {
            get {
                return ResourceManager.GetString("ErrorPostcodeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check that you have correctly entered an East Sussex postcode or add your address manually.
        /// </summary>
        internal static string ErrorRecheckAddress {
            get {
                return ResourceManager.GetString("ErrorRecheckAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some of the characters in the first line of your address are not allowed.
        /// </summary>
        internal static string ErrorSaonFormat {
            get {
                return ResourceManager.GetString("ErrorSaonFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please use 100 characters or fewer in the first line of your address.
        /// </summary>
        internal static string ErrorSaonLength {
            get {
                return ResourceManager.GetString("ErrorSaonLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some of the characters in the third line of your address are not allowed.
        /// </summary>
        internal static string ErrorStreetDescriptorFormat {
            get {
                return ResourceManager.GetString("ErrorStreetDescriptorFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please use 100 characters or fewer in the third line of your address.
        /// </summary>
        internal static string ErrorStreetDescriptorLength {
            get {
                return ResourceManager.GetString("ErrorStreetDescriptorLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some of the characters in the town name are not allowed.
        /// </summary>
        internal static string ErrorTownFormat {
            get {
                return ResourceManager.GetString("ErrorTownFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please use 30 characters or fewer in the town name.
        /// </summary>
        internal static string ErrorTownLength {
            get {
                return ResourceManager.GetString("ErrorTownLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you have an East Sussex postcode type it in the text box below and use the &apos;Find Address&apos; button to complete your address details..
        /// </summary>
        internal static string FindAddressIntro {
            get {
                return ResourceManager.GetString("FindAddressIntro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to or.
        /// </summary>
        internal static string FindAddressOr {
            get {
                return ResourceManager.GetString("FindAddressOr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        internal static string GenderEntryPrompt {
            get {
                return ResourceManager.GetString("GenderEntryPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to House name or number.
        /// </summary>
        internal static string HouseEntryPrompt {
            get {
                return ResourceManager.GetString("HouseEntryPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the name or number of your house.
        /// </summary>
        internal static string HouseRequiredError {
            get {
                return ResourceManager.GetString("HouseRequiredError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Village or part of town.
        /// </summary>
        internal static string LocalityLabel {
            get {
                return ResourceManager.GetString("LocalityLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type address.
        /// </summary>
        internal static string ManualAddress {
            get {
                return ResourceManager.GetString("ManualAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the month.
        /// </summary>
        internal static string MonthSelectPopupText {
            get {
                return ResourceManager.GetString("MonthSelectPopupText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t have a postcode?.
        /// </summary>
        internal static string NoPostcodePrompt {
            get {
                return ResourceManager.GetString("NoPostcodePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Building name or number.
        /// </summary>
        internal static string PaonLabel {
            get {
                return ResourceManager.GetString("PaonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to William Shakespeare&apos;s in my cat.
        /// </summary>
        internal static string PasswordKey {
            get {
                return ResourceManager.GetString("PasswordKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid postcode.
        /// </summary>
        internal static string PostcodeESCCInvalidError {
            get {
                return ResourceManager.GetString("PostcodeESCCInvalidError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter an East Sussex postcode.
        /// </summary>
        internal static string PostcodeESCCRequiredError {
            get {
                return ResourceManager.GetString("PostcodeESCCRequiredError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid UK postcode.
        /// </summary>
        internal static string PostcodeInvalidError {
            get {
                return ResourceManager.GetString("PostcodeInvalidError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postcode.
        /// </summary>
        internal static string PostcodeLabel {
            get {
                return ResourceManager.GetString("PostcodeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *.
        /// </summary>
        internal static string RequiredFieldIndicator {
            get {
                return ResourceManager.GetString("RequiredFieldIndicator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  means information is required.
        /// </summary>
        internal static string RequiredFieldIndicatorHelp {
            get {
                return ResourceManager.GetString("RequiredFieldIndicatorHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flat number or firm.
        /// </summary>
        internal static string SaonLabel {
            get {
                return ResourceManager.GetString("SaonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select the correct address:.
        /// </summary>
        internal static string SelectAddress {
            get {
                return ResourceManager.GetString("SelectAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Street name.
        /// </summary>
        internal static string StreetLabel {
            get {
                return ResourceManager.GetString("StreetLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number.
        /// </summary>
        internal static string TelNumber {
            get {
                return ResourceManager.GetString("TelNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Town.
        /// </summary>
        internal static string TownLabel {
            get {
                return ResourceManager.GetString("TownLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the year.
        /// </summary>
        internal static string YearSelectPopupText {
            get {
                return ResourceManager.GetString("YearSelectPopupText", resourceCulture);
            }
        }
    }
}
